### ISSUE TITLE
JSON RPC error data can be omitted

### ISSUE THREAD

**Issue by hrls** [velas/velas-chain#160]
#### Problem
Server got error response without `data` and then wrap it into another with reason _missing data_.
But [JSON RPC spec](https://www.jsonrpc.org/specification#error_object) says:
> This may be omitted.

https://github.com/velas/velas-chain/blob/develop/client/src/http_sender.rs#L36

#### Proposed Solution
Make `RpcErrorObject.data` optional. Or `"data": null"`. Or TBD

**Comment by hrls** [comment]
```json
{
  "level": 20,
  "time": 1625237818775,
  "msg": "Returned error: Failed to execute request, rpc return error: RPC request error: Failed to deserialize RPC error response: {\"code\":-32005,\"message\":\"ServerError(-32005)\"} [missing field `data`]",
  "name": "watcher-native-erc-signature-request",
  "module": "web3",
  "type": "Error",
  "stack": "Error: Returned error: Failed to execute request, rpc return error: RPC request error: Failed to deserialize RPC error response: {\"code\":-32005,\"message\":\"ServerError(-32005)\"} [missing field `data`]\n    at Object.ErrorResponse (/mono/node_modules/web3-core-helpers/lib/errors.js:28:19)\n    at /mono/node_modules/web3-core-requestmanager/lib/index.js:288:36\n    at HttpListProvider.send (/mono/oracle/src/services/HttpListProvider.js:73:5)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
  "data": "ClientError { request: Some(EthGetLogs), kind: RpcError(RpcRequestError(\"Failed to deserialize RPC error response: {\\\"code\\\":-32005,\\\"message\\\":\\\"ServerError(-32005)\\\"} [missing field `data`]\")) }",
  "v": 1
}
```

Original error from @Levchks
